apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rakshitha-mayya/sample-nginx-helm-chart.git
    path: charts
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      values: |
        replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated: {}
