apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: app-deployment
  title: App Deployment
  description: Deploys an application to a selected cluster using details from deploy-iac-template.
  tags:
    - backstage
    - app
    - github
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Cluster Selection
      required:
        - clusterName
      properties:
        clusterName:
          title: Cluster Name
          type: string

  steps:
    - id: fetch-cluster-details
      name: Fetch Cluster Details
      action: fetch:plain
      input:
        url: ./Infrastructure/deploy-iac-template
        targetPath: ./cluster-details.txt

    - id: parse-cluster-details
      name: Parse Cluster Details
      action: script:run
      input:
        script: |
          #!/bin/bash
          grep "${{ parameters.clusterName }}" ./cluster-details.txt > ./selected-cluster.txt

    # Add your deployment steps here, using ./selected-cluster.txt as input

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
